---
- name: Gather info
  hosts: all
  gather_facts: no
  tasks:
    - name: Get ESXi build version (simplified)
      command: esxcli system version get | grep "Build"
      register: build_output
      ignore_errors: yes

    - name: Set needs_patch fact based on build number example
      set_fact:
        needs_patch: "{{ '20036589' not in build_output.stdout }}"

- name: Select one unpatched host per cluster dynamically
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get cluster groups
      set_fact:
        cluster_names: "{{ groups.keys() | select('match', '^cluster_') | list }}"

    - name: Build cluster to unpatched hosts map
      set_fact:
        cluster_to_unpatched_hosts: "{{ dict(cluster_names | zip(cluster_names | map('extract', groups) | map('selectattr', 'needs_patch') | map('list'))) }}"

    - name: Pick one unpatched host per cluster
      set_fact:
        hosts_to_patch: "{{ cluster_to_unpatched_hosts | dict2items | map(attribute='value') | map('random') | list }}"

    - name: Add selected hosts to patch_hosts group
      add_host:
        name: "{{ item }}"
        groups: patch_hosts
      loop: "{{ hosts_to_patch }}"

- name: Patch selected hosts in parallel
  hosts: patch_hosts
  gather_facts: no
  serial: 5
  tasks:
    - name: Gather NTP info about ESXi Host
      community.vmware.vmware_host_ntp_info:
        hostname: "bvcewvvc9801.berrylabs.com"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        esxi_hostname: '{{ inventory_hostname }}'
      delegate_to: localhost
      register: host_ntp